version: 2.1

executors:
  builder:
    machine: true

workflows:
  
  getsbom_and_triage:
    jobs:
      - osv_scan:
          context: leanseeks

jobs:
  osv_scan:
    executor: builder
    environment:
      owner: "macnicadevops"
      repo: "macnicadevops.github.io"

    steps:
      - checkout
                     
      - run:
          name: Prepare environment
          command: |
            apt-get update && apt-get install -y curl golang git python3 python3-pip
            pip install --upgrade pip
            go install github.com/google/osv-scanner/cmd/osv-scanner@v1
            pip3 install cvss

      - run:
          name: "OSV Scanner"
          command: |
            chmod +x getSBOM.sh triage.sh
            ./getSBOM.sh
            ./triage.sh
          
